open Astring

let print_header () =
  Format.printf "@[<v>;; This file was auto-generated by [%s]@,@,@]" __FILE__

type mode =
  | Lib_gen  (** Generate executable stanzas for the stub generators *)
  | Lib_bindings  (** Generate library stanzas each for the bindings *)

let generator_module_of_file x = x ^ "_gen"

let chop_suffix_opt name ~suffix =
  match Filename.check_suffix name suffix with
  | false -> None
  | true -> Some (Filename.chop_suffix name suffix)

let chop_suffix_exn name ~suffix =
  match chop_suffix_opt name ~suffix with
  | Some s -> s
  | None ->
      Format.kasprintf failwith "File %s doesn't have the expected suffix: %s"
        name suffix

let rec pp_list pp_elt ppf = function
  | [] -> ()
  | [ x ] -> pp_elt ppf x
  | x :: xs ->
      pp_elt ppf x;
      Format.pp_print_space ppf ();
      pp_list pp_elt ppf xs

let executable_name = Printf.sprintf "%s_gen"
let bindings_name = Printf.sprintf "%s_bindings"
let stubs_name = Printf.sprintf "%s_stubs"
let bindings_library_name = Printf.sprintf "hacl-star-raw.%s_bindings"
let stubs_library_name = Printf.sprintf "hacl-star-raw.%s_stubs"

let print_generator_stanzas =
  List.iter (fun name ->
      let executable_name = executable_name name in
      let library_name = bindings_library_name name in
      Format.printf
        "@[<v 1>(executable@,\
         (name %s)@,\
         (modules %s)@,\
         (libraries@ ctypes@ ctypes.stubs@ %s))@]@.@." executable_name
        executable_name library_name)

let print_library_stanzas deps =
  Format.printf
    "@[<v 1>(library@,\
     (name hacl_star_raw)@,\
     (public_name hacl-star-raw)@,\
     (modules)@,\
     @[<v 1>(libraries@ %a)@])@]@.@."
    (pp_list Format.pp_print_string)
    (List.concat_map
       (fun n ->
         [
           n;
           String.Sub.to_string (String.sub ~stop:(String.length n - 9) n)
           ^ "_stubs";
         ])
       (List.of_seq (Hashtbl.to_seq_keys deps)));

  List.iter (fun name ->
      (* Printf.eprintf "Trying to find: %s\n%!" name; *)
      let deps = Hashtbl.find deps (bindings_library_name name) in
      Format.printf
        ";; ----------------------------------@.;; %s@.;; \
         ----------------------------------@.@.@[<v 1>(library@,\
         (name %s)@,\
         (modules %s)@,\
         (public_name %s)@,\
         (wrapped false)@,\
         (flags (:standard -w -27-33 -warn-error -A))@,\
         @[<1>(libraries@ ctypes@ %a)@])@]@.@." name (bindings_name name)
        (bindings_name name)
        (bindings_library_name name)
        (pp_list Format.pp_print_string)
        deps;

      let local_name =
        if Sys.file_exists (name ^ ".c") then name ^ " " else ""
      in

      Format.printf
        "@[<v 1>(library@,\
         (name %s)@,\
         (modules %s)@,\
         (public_name %s)@,\
         (wrapped false)@,\
         @[<v 1>(foreign_stubs@,\
         (language c)@,\
         (names %s%s)@,\
         @[<1>(flags (:standard@ -Wno-parentheses@ \
         -Wno-deprecated-declarations@ -Wno-#warnings@ -Wno-error=cpp@ \
         -Wno-cpp@ -g@ -std=gnu11@ -O3))@]@,\
         (include_dirs . kremlin/include kremlin/kremlib/dist/minimal))@]@,\
         (libraries ctypes ctypes.stubs))@]@.@." (stubs_name name)
        (stubs_name name) (stubs_library_name name) local_name
        (name ^ "_c_stubs");

      Format.printf
        "@[<v 1>(rule@,\
         (targets %s.c %s.ml)@,\
         @[<v 1>(action@,\
         @[<v 1>(chdir ../@,\
         (run lib_gen/%s.exe))))@]@]@]@]@.@." (name ^ "_c_stubs")
        (stubs_name name) (executable_name name))

let read_dependencies path =
  let ic = Scanf.Scanning.open_in path in
  let () = Scanf.bscanf ic "%_s@\n" () in
  let depends = Hashtbl.create 0 in
  let lib_name n =
    try Scanf.sscanf n "lib/%s@.cmx" (fun x -> Some ("hacl-star-raw." ^ x)) with
    | Scanf.Scan_failure _ -> None
    | End_of_file -> None
  in
  let rec process_lines () =
    Scanf.bscanf ic "%s@\n" @@ fun line ->
    let line = line ^ "\n" in
    Scanf.sscanf line "%s@: %s@\n" @@ fun target deps ->
    (match lib_name target with
    | None -> ()
    | Some target ->
        let deps = String.fields deps |> List.filter_map lib_name in
        (* Format.eprintf "Scanning line: %s\n" line;
         * Format.eprintf "%s <- %a\n%!" target
         *   (pp_list Format.pp_print_string)
         *   deps; *)
        Hashtbl.add depends target deps);
    if not (Scanf.Scanning.end_of_input ic) then process_lines ()
  in
  process_lines ();
  depends

let () =
  let mode =
    match Sys.argv with
    | [| _; "--lib-bindings"; _ |] -> Lib_bindings
    | [| _; "--lib-gen"; _ |] -> Lib_gen
    | _ ->
        Format.eprintf "Usage: %s [--lib | --lib-gen] <ctypes.depend>"
          Sys.argv.(0);
        exit 1
  in
  let path = Sys.argv.(2) in
  match mode with
  | Lib_gen ->
      let modules =
        Sys.readdir "."
        |> Array.to_list
        |> List.filter_map (chop_suffix_opt ~suffix:"_gen.ml")
        |> List.sort String.compare
      in
      print_header ();
      print_generator_stanzas modules
  | Lib_bindings ->
      let deps = read_dependencies path in
      let modules =
        Sys.readdir "."
        |> Array.to_list
        |> List.filter_map (chop_suffix_opt ~suffix:"_bindings.ml")
        |> List.sort String.compare
      in
      print_header ();
      (* Format.printf "(copy_files (alias header_files) (files ../*.h))@.@."; *)
      print_library_stanzas deps modules
